[feature list]


[combat tab]
  [silent aim]
    [master toggle]
    [wallcheck]
    [hit-chance]
    [fov circle]
  [trigger-bot]
    [master toggle]
    [delay %ms]
    [fov circle]

  [gun mods]
    [mega-bullet]
    [firerate]
    [bullet-count]
    [wallbang] -- doesnt work with silent aim :/
[visuals tab]
  [enemy]
    [master toggle]
    [2d box]
    [healthbar]
    [name text]
    [distance text]
    [weapon text]
    [armor value %]
    [velocity value %]
  [world]
    [ambience %]
    [brightness %]
    [fog %]
[local player tab]
  [movement]
    [flight]
    [flight speed]
    [tpwalk]
    [tpwalk speed
  [character]
    [anti-aim]
    [anti-aim pitch, yaw and degree]
    [noclip]
    [anchor character]
